# This script uses a source file that is generated by the litter code to sum weights by trap. That code is called "Litter code to sum weights by trap by date"
#This script is the second script you should run. 

# Load some important libraries that contain functions you might use
# Before you start, make sure these are downloaded and up-to-date
library(ggplot2)
library(RColorBrewer)
library(gridExtra)
library(reshape2)
library(lubridate)
library(plyr)

# Read in the litter dataset
litter.trap <- read.csv('Z:/eddyflux/Tower sites/All_Sites/Biomass_All_Sites/Litter_Biomass_All_Sites/Litter QC in R/Litter NPP Calculations/temporary file for Litter plot files/trap_weight.csv')
head(litter.trap)



annual.weight <- ddply(litter.trap, c("Site", "Transect" , "TransectDistance" , "Year" , "CoveredOpen" , "CoverType" , "Trap" ), function(x)
  data.frame(annualtrapweight = colSums(x["totalweight"], na.rm=T) /
               length(unique("Trap" )),
             varweight = var(x$totalweight, na.rm=T)))
             

             
head(annual.weight)
write.csv(annual.weight, 'Z:/eddyflux/Tower sites/All_Sites/Biomass_All_Sites/Litter_Biomass_All_Sites/Litter QC in R/Litter NPP Calculations/temporary file for Litter plot files/annual weight per trap.csv', row.names=F)

meanannual.weight <- ddply(litter.trap, c("Site", "Transect" , "TransectDistance" , "Year" , "CoveredOpen" , "CoverType" , "Trap" ), function(x)
  data.frame(meanannualtrapweight = mean(x["totalweight"], na.rm=T) /
               length(unique("Trap" )),
             varweight = var(x$totalweight, na.rm=T)))

head(manannual.weight)

